version: "3.9"

services:
  mongo_db:
    container_name: db_container
    image: mongo:6.0         # use a stable tag instead of floating "latest"
    restart: always
    ports:
      - "27017:27017"        # expose only if you need to connect locally (Studio 3T, Compass, etc.)
    volumes:
      - mongo_data:/data/db
    networks:
      - backend
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile   # expects Dockerfile in server/database
    image: nodeapp:latest      # optional tag
    restart: always
    ports:
      - "3030:3030"
    depends_on:
      mongo_db:
        condition: service_healthy
    environment:
      - MONGO_URL=mongodb://mongo_db:27017/dealershipsDB
      - PORT=3030
    networks:
      - backend

volumes:
  mongo_data:

networks:
  backend:
    driver: bridge
