apiVersion: v1
kind: Secret
metadata:
  name: django-superuser-secret
type: Opaque
stringData:
  username: emifeaustin
  email: emifeaustin0909@gmail.com
  password: dealership123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealership
  labels:
    run: dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dealership
  template:
    metadata:
      labels:
        run: dealership
    spec:
      containers:
        - name: dealership
          image: us.icr.io/sn-labs-emifeaustin0/dealership:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: djangoproj.settings
            - name: backend_url
              value: http://dealership-api:3030
            - name: sentiment_analyzer_url
              value: https://sentianalyzer.1zsxdruquzxr.us-south.codeengine.appdomain.cloud/
            - name: DJANGO_SUPERUSER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: django-superuser-secret
                  key: username
            - name: DJANGO_SUPERUSER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: django-superuser-secret
                  key: email
            - name: DJANGO_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: django-superuser-secret
                  key: password
          livenessProbe:
            httpGet:
              path: /admin/
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /admin/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
