apiVersion: apps/v1
kind: Deployment
metadata:
  name: dealership
  labels:
    run: dealership
spec:
  replicas: 1
  selector:
    matchLabels:
      run: dealership
  template:
    metadata:
      labels:
        run: dealership
    spec:
      containers:
        - name: dealership
          image: us.icr.io/sn-labs-emifeaustin0/dealership:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: djangoproj.settings
            - name: backend_url
              value: http://dealership-api:3030
            - name: sentiment_analyzer_url
              value: https://sentianalyzer.1zsxdruquzxr.us-south.codeengine.appdomain.cloud/
